# Generated by Django 4.2.20 on 2025-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='type',
            field=models.CharField(choices=[('O', 'Other'), ('A', 'Amplifier'), ('B', 'Bass'), ('G', 'Guitar'), ('P', 'Percussion')], default='O', max_length=1),
        ),
    ]
